[package]
name = "neuron"
version = "0.1.0"
authors = ["cbr9 <cabero96@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
